/**
 * Public-domain piano pieces for the login hero.
 *
 * COPYRIGHT: every piece here is a public-domain composition — Bach (d. 1750)
 * and Beethoven (d. 1827), published long before 1928. The audio is SYNTHESIZED
 * in-browser from these note numbers (see PianoSynth.js), so there is no
 * sound-recording copyright either: no sample, no master, nothing licensed.
 *
 * TWO HANDS, ONE RIG. The hero renders a single hand, and it plays the LEFT-hand
 * part. The right-hand melody still sounds, it just has no fingers to drive:
 * there is no second hand to render, and faking it on the left hand would look
 * worse than leaving it to the ear. Notes are therefore tagged "L" (audible AND
 * played by the visible hand) or "R" (audible only).
 *
 * Both pieces here have ARPEGGIATED left hands — one note at a time. Block-chord
 * pieces (Canon in D, Ode to Joy) were tried and removed: several fingers landing
 * at once never read convincingly, because at the tuned camera angle the keys run
 * nearly parallel to the finger spread, so a three-note chord lit roughly one key.
 * compileSong still handles simultaneous notes (see the chord grip below) if a
 * chordal piece is ever added back.
 *
 * Authoring format — `{ id, title, composer, step, notes }` where a note is
 * `[unit, midi, durUnits, hand]` and `step` is seconds per unit. Times in units
 * keep the data readable (a unit is whatever subdivision the piece wants);
 * compileSong() converts to seconds. Pieces built on a repeating figure are
 * generated by a small function rather than typed out — same data, far less
 * room for a transcription slip.
 */

// --- Prelude in C (Bach, WTC I) ---------------------------------------------
// Every bar is one broken chord stated TWICE, written out in full. Within each
// half the left hand lays down its two notes and holds them while the right hand
// plays its three above, then repeats that same three-note group.
//
// Pitches verified against the Humdrum kern, LilyPond and MusicXML editions of
// BWV 846: the left hand sits on MIDDLE C, not the C below it. An earlier version
// of this data was a full octave low, which both darkened the piece and made the
// synth's bass ring (which lengthens with depth) muddy the arpeggio.
function preludeInC() {
  const bars = [
    { L: [60, 64], R: [67, 72, 76] }, // m1  C      — C4 E4 / G4 C5 E5
    { L: [60, 62], R: [69, 74, 77] }, // m2  Dm7/C  — C4 D4 / A4 D5 F5
    { L: [59, 62], R: [67, 74, 77] }, // m3  G7/B   — B3 D4 / G4 D5 F5
    { L: [60, 64], R: [67, 72, 76] }, // m4  C      — C4 E4 / G4 C5 E5
  ];
  const notes = [];
  bars.forEach((bar, b) => {
    for (let half = 0; half < 2; half++) {
      const u = b * 16 + half * 8;
      notes.push([u, bar.L[0], 8, "L"]); // bass rings under the whole figure
      notes.push([u + 1, bar.L[1], 7, "L"]);
      // Each RH note is a sixteenth and lasts a sixteenth — this is a running
      // arpeggio, not a held chord. Only the LH sustains underneath.
      bar.R.forEach((m, i) => notes.push([u + 2 + i, m, 1, "R"]));
      bar.R.forEach((m, i) => notes.push([u + 5 + i, m, 1, "R"]));
    }
  });
  return notes;
}

export const SONGS = [
  {
    id: "fur-elise",
    title: "Für Elise",
    composer: "Beethoven",
    step: 0.165, // one sixteenth; 3/8, so a measure is 6 units
    // Transcribed from the Mutopia Project LilyPond source (typeset from
    // Breitkopf & Härtel, 1888), anacrusis through m. 8. Two independent
    // transcriptions agreed on all 53 notes.
    //
    // Two things here were previously wrong and are worth stating so they are
    // not "corrected" back. (1) The LH arpeggio enters ON the downbeat, at the
    // same instant as the RH's A4 — not later in the bar. (2) The ascending
    // C4-E4-A4 and E4-G#4-B4 figures are RIGHT hand, notated in the treble
    // staff; they are low, which is what makes them look like left-hand
    // material. Assigning them to the LH is what pushed the real LH part late.
    notes: [
      // pickup + m1 — RH: E D# E D# E B D C
      [0, 76, 1, "R"], [1, 75, 1, "R"], [2, 76, 1, "R"], [3, 75, 1, "R"],
      [4, 76, 1, "R"], [5, 71, 1, "R"], [6, 74, 1, "R"], [7, 72, 1, "R"],
      // m2 — RH A4 over the LH A-minor arpeggio, struck together
      [8, 69, 2, "R"], [8, 45, 1, "L"], [9, 52, 1, "L"], [10, 57, 1, "L"],
      [11, 60, 1, "R"], [12, 64, 1, "R"], [13, 69, 1, "R"], // RH C4 E4 A4
      // m3 — RH B4 over the LH E-major arpeggio
      [14, 71, 2, "R"], [14, 40, 1, "L"], [15, 52, 1, "L"], [16, 56, 1, "L"],
      [17, 64, 1, "R"], [18, 68, 1, "R"], [19, 71, 1, "R"], // RH E4 G#4 B4
      // m4 — RH C5, LH back to A minor
      [20, 72, 2, "R"], [20, 45, 1, "L"], [21, 52, 1, "L"], [22, 57, 1, "L"],
      [23, 64, 1, "R"],
      // m5-m6 — the opening figure returns
      [24, 76, 1, "R"], [25, 75, 1, "R"], [26, 76, 1, "R"], [27, 75, 1, "R"],
      [28, 76, 1, "R"], [29, 71, 1, "R"], [30, 74, 1, "R"], [31, 72, 1, "R"],
      [32, 69, 2, "R"], [32, 45, 1, "L"], [33, 52, 1, "L"], [34, 57, 1, "L"],
      [35, 60, 1, "R"], [36, 64, 1, "R"], [37, 69, 1, "R"],
      // m7
      [38, 71, 2, "R"], [38, 40, 1, "L"], [39, 52, 1, "L"], [40, 56, 1, "L"],
      [41, 64, 1, "R"], [42, 72, 1, "R"], [43, 71, 1, "R"],
      // m8 — cadence on A
      [44, 69, 4, "R"], [44, 45, 1, "L"], [45, 52, 1, "L"], [46, 57, 1, "L"],
    ],
  },
  {
    id: "prelude-in-c",
    title: "Prelude in C",
    composer: "Bach",
    step: 0.19, // one sixteenth
    notes: preludeInC(),
  },
];

import { midiToKey, whiteIndex, keyId } from "./pianoKeys";

// Where a song's lowest left-hand note should sit on the renderer's drawn key
// slots. The actual placement lands between this and this+6, because the offset
// is snapped DOWN to a whole octave to keep pitch classes aligned.
const TARGET_LOW_SLOT = 2;

const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

/**
 * Turn authoring data into everything the player and the canvas need.
 *
 * FINGER ASSIGNMENT IS GESTURAL, NOT PITCH-ACCURATE — deliberately. The hand
 * only drifts ~±26px (PIANO_SHIFT × 2) while a part can span an octave or more,
 * and the keyboard is sized and placed relative to the hand, so literally
 * tracking pitch would slide the hand out from under its own keys. Each
 * left-hand note is instead ranked inside the left-hand part's own range and
 * mapped to one of the five fingers: the eye reads the RHYTHM and the CONTOUR,
 * while the audio carries the true pitch.
 *
 * Right-hand notes are returned in `notes` (so they sound) but are absent from
 * `events` / `strikeSpans`, so they drive no finger.
 *
 * Returns { notes, events, strikeSpans, duration } with all times in SECONDS.
 */
export function compileSong(song) {
  const { step } = song;

  const notes = song.notes
    .map(([unit, midi, durUnits, hand]) => {
      if (!(durUnits > 0)) {
        // A zero or negative duration makes the strike envelope discontinuous
        // and is always an authoring slip. Fail loudly at the source rather than
        // letting it become a visual glitch nobody can trace back.
        throw new Error(
          `${song.id}: note ${midi} at unit ${unit} has duration ${durUnits}; must be > 0`,
        );
      }
      return { t: unit * step, midi, dur: durUnits * step, hand, finger: null };
    })
    .sort((a, b) => a.t - b.t || a.midi - b.midi);

  const left = notes.filter((n) => n.hand === "L");
  const lo = left.length ? Math.min(...left.map((n) => n.midi)) : 0;
  const hi = left.length ? Math.max(...left.map((n) => n.midi)) : 1;
  const span = Math.max(1, hi - lo);
  // LEFT-HAND FINGERING IS INVERTED relative to a right hand: the pinky takes the
  // LOWEST notes and the thumb the highest. FINGERS is [thumb, index, middle,
  // ring, pinky], so the lowest pitch maps to 4 and the highest to 0. Getting
  // this backwards is immediately obvious to anyone who plays — the index finger
  // ends up reaching for bass notes the pinky should be on.
  for (const n of left) n.finger = 4 - Math.round(((n.midi - lo) / span) * 4);

  // Group the left hand by strike time — a chord is one event, not three.
  const byTime = new Map();
  for (const n of left) {
    const key = n.t.toFixed(4);
    if (!byTime.has(key)) byTime.set(key, []);
    byTime.get(key).push(n);
  }
  const groups = [...byTime.values()].sort((a, b) => a[0].t - b[0].t);

  let prevFinger = null;
  let prevMidi = null;
  for (const g of groups) {
    if (g.length === 1) {
      const n = g[0];
      // A real player wouldn't restrike one finger across a pitch change (think
      // of the E–D# trill in Für Elise: it alternates). Where the rank mapping
      // repeats a finger, step in the direction the line moved.
      if (prevMidi !== null && n.midi !== prevMidi && n.finger === prevFinger) {
        // Rising pitch moves TOWARD THE THUMB on a left hand, i.e. toward a lower
        // finger index — the opposite of the right-hand instinct.
        const dir = n.midi > prevMidi ? -1 : 1;
        let f = prevFinger + dir;
        // Already on the outermost finger — stepping further would clamp back
        // onto the same one and read as a repeat. Go the other way instead, as
        // a player shifting hand position would.
        if (f < 0 || f > 4) f = prevFinger - dir;
        n.finger = clamp(f, 0, 4);
      }
    } else {
      // A chord: one finger cannot strike two keys, so hand out distinct adjacent
      // fingers around where the rank mapping put the chord. Ordering is
      // left-hand: the LOWEST note of the chord takes the highest finger index
      // (the pinky) and pitch rises toward the thumb — so a bass-plus-chord grip
      // spans the hand the way a real one does.
      g.sort((a, b) => a.midi - b.midi);
      if (g.length > 5) g.length = 5;
      const mean = g.reduce((s, n) => s + n.finger, 0) / g.length;
      const start = clamp(Math.round(mean - (g.length - 1) / 2), 0, 5 - g.length);
      g.forEach((n, i) => { n.finger = start + (g.length - 1 - i); });
    }
    const last = g[g.length - 1];
    prevFinger = last.finger;
    prevMidi = last.midi;
  }

  // Per finger: [onset, howLongItIsHeld] — NOT just onsets. A finger has to stay
  // down for as long as its note sounds, or the hand blips for a fraction of a
  // second and then sits frozen while you can still hear the note ringing.
  const strikeSpans = [[], [], [], [], []];
  for (const g of groups) for (const n of g) strikeSpans[n.finger].push([n.t, n.dur]);
  for (const arr of strikeSpans) arr.sort((a, b) => a[0] - b[0]);

  // WHICH KEY GOES DOWN, per note. This is deliberately NOT derived from where a
  // fingertip happens to land: at the tuned camera angle the hand's lateral
  // travel carries about 0.04 key slots of authority against 4-10 slots of noise
  // from the wrist hinge alone, so finger geometry cannot address a key (see
  // pianoKeys.js). Driving the press from the note instead makes the lit key a
  // pure function of the music — stable under breathing, wrist sway and resize.
  //
  // Keys are ABSOLUTE white-key indices. `keyOffset` is what the renderer
  // subtracts to place them on its drawn slots, and it MUST be a whole number of
  // octaves.
  //
  // The renderer's keyboard carries an implicit pitch identity: it draws a black
  // key after every slot k where k mod 7 is one of {0,1,3,4,5}, which is the
  // C-D-F-G-A pattern — so drawn slot k IS the natural [C,D,E,F,G,A,B][k mod 7].
  // Shifting by anything other than a multiple of 7 rotates the whole keyboard
  // against its own black keys, and every note lights a wrongly-named key. An
  // earlier version anchored slot 0 on the song's lowest note, which has no
  // relationship to C: Für Elise's G#3 came out on the key drawn as F#, and in
  // fact all nine distinct keys across the two pieces were wrong.
  const keySpans = new Map(); // keyId -> [[onset, held], ...]
  let keyOffset = 0;
  if (left.length) {
    // Drop the played range down to around TARGET_LOW_SLOT, in whole octaves.
    keyOffset = 7 * Math.floor((whiteIndex(lo) - TARGET_LOW_SLOT) / 7);
    for (const n of left) {
      n.key = midiToKey(n.midi); // absolute
      const id = keyId(n.key);
      if (!keySpans.has(id)) keySpans.set(id, { ...n.key, spans: [] });
      keySpans.get(id).spans.push([n.t, n.dur]);
    }
    for (const entry of keySpans.values()) entry.spans.sort((a, b) => a[0] - b[0]);
  }

  // `lat` (mean finger, centred on the middle finger) is the legacy drift used by
  // the idle phrase. `aimKey`/`aimFinger` are what a playing song uses instead:
  // the key the hand should travel to, and which finger should land on it. The
  // lowest note anchors a chord, as it does under a real hand.
  const events = groups.map((g) => {
    const f = g.map((n) => n.finger);
    const anchor = g.reduce((lo, n) => (n.midi < lo.midi ? n : lo), g[0]);
    return {
      t: g[0].t,
      f,
      lat: f.reduce((s, x) => s + x, 0) / f.length - 2,
      aimKey: anchor.key,
      aimFinger: anchor.finger,
    };
  });

  // The piece is over when the LAST-ENDING note finishes — not when the last
  // note STARTS. Those differ whenever a held note is struck before shorter
  // ones: Für Elise's closing A4 is struck on the downbeat and rings under the
  // three-note LH arpeggio that follows it, so keying off the final onset would
  // cut the piece off while its own last chord was still sounding.
  const endsAt = notes.reduce((m, n) => Math.max(m, n.t + Math.max(n.dur, 0.6)), 0);
  const duration = endsAt + 0.5;

  // The key the hand's REST pose corresponds to: the MIDDLE of the played
  // range, not its bottom. Travel is a displacement from here, so the hand sits
  // at home mid-range and glides half the span either way — anchoring on the
  // lowest note instead pushes the whole motion one-directional and walks the
  // hand off the frame at the top of the range.
  //
  // Measured at 1600x900, this framing separates adjacent keys ~5:1 VERTICALLY
  // on screen (74px across vs 354px down over Für Elise's left hand) while the
  // hand's fingers spread ~3:1 HORIZONTALLY (276px across, 82px down). The two
  // axes are near perpendicular, so a specific finger cannot be parked on a
  // specific key without dragging the hand into the corner. What the hand can
  // do — and what a side view of a pianist actually looks like — is glide along
  // the key axis so the playing region tracks the note.
  // Centre on the midpoint of the KEY SPAN, not the median pitch: the median
  // note of Für Elise's left hand sits 7 keys above its lowest and only 3 below
  // its highest, which would bias the whole glide downward.
  // The anchor need not be a key the piece actually plays — it is only the
  // origin the glide is measured from, so use the exact midpoint of the span.
  // Snapping it to the nearest played key re-introduces the bias it exists to
  // remove (Für Elise's played keys tie either side of its own midpoint).
  let aimRef = null;
  if (left.length) {
    const whites = left.map((n) => n.key.white);
    aimRef = { white: Math.round((Math.min(...whites) + Math.max(...whites)) / 2), black: false };
  }

  return { notes, events, strikeSpans, keys: [...keySpans.values()], keyOffset, aimRef, duration };
}
