/**
 * Public-domain piano pieces for the login hero.
 *
 * COPYRIGHT: every piece here is a public-domain composition — Bach (d. 1750)
 * and Beethoven (d. 1827), published long before 1928. The audio is SYNTHESIZED
 * in-browser from these note numbers (see PianoSynth.js), so there is no
 * sound-recording copyright either: no sample, no master, nothing licensed.
 *
 * TWO HANDS, ONE RIG. The hero renders a single hand, and it plays the LEFT-hand
 * part. The right-hand melody still sounds, it just has no fingers to drive:
 * there is no second hand to render, and faking it on the left hand would look
 * worse than leaving it to the ear. Notes are therefore tagged "L" (audible AND
 * played by the visible hand) or "R" (audible only).
 *
 * Both pieces here have ARPEGGIATED left hands — one note at a time. Block-chord
 * pieces (Canon in D, Ode to Joy) were tried and removed: several fingers landing
 * at once never read convincingly, because at the tuned camera angle the keys run
 * nearly parallel to the finger spread, so a three-note chord lit roughly one key.
 * compileSong still handles simultaneous notes (see the chord grip below) if a
 * chordal piece is ever added back.
 *
 * Authoring format — `{ id, title, composer, step, notes }` where a note is
 * `[unit, midi, durUnits, hand]` and `step` is seconds per unit. Times in units
 * keep the data readable (a unit is whatever subdivision the piece wants);
 * compileSong() converts to seconds. Pieces built on a repeating figure are
 * generated by a small function rather than typed out — same data, far less
 * room for a transcription slip.
 */

// --- Prelude in C (Bach, WTC I) ---------------------------------------------
// Every bar is one broken chord played twice: the left hand lays down two low
// notes and holds them while the right hand arpeggiates above.
function preludeInC() {
  const bars = [
    { L: [48, 52], R: [55, 60, 64] }, // C
    { L: [48, 50], R: [57, 62, 65] }, // Dm7/C
    { L: [47, 50], R: [55, 62, 65] }, // G7/B
    { L: [48, 52], R: [55, 60, 64] }, // C
  ];
  const notes = [];
  bars.forEach((bar, b) => {
    for (let half = 0; half < 2; half++) {
      const u = b * 16 + half * 8;
      notes.push([u, bar.L[0], 8, "L"]); // bass rings under the whole figure
      notes.push([u + 1, bar.L[1], 7, "L"]);
      bar.R.forEach((m, i) => notes.push([u + 2 + i, m, 2, "R"]));
      bar.R.forEach((m, i) => notes.push([u + 5 + i, m, 2, "R"]));
    }
  });
  return notes;
}

export const SONGS = [
  {
    id: "fur-elise",
    title: "Für Elise",
    composer: "Beethoven",
    step: 0.165, // one sixteenth
    // Melody in the right hand; the left hand answers with the A-minor and
    // E-major arpeggios that sit under it.
    notes: [
      [0, 76, 1, "R"], [1, 75, 1, "R"], [2, 76, 1, "R"], [3, 75, 1, "R"],
      [4, 76, 1, "R"], [5, 71, 1, "R"], [6, 74, 1, "R"], [7, 72, 1, "R"],
      [8, 69, 3, "R"],
      [11, 45, 1, "L"], [12, 52, 1, "L"], [13, 57, 1, "L"], // A2 E3 A3
      [14, 71, 3, "R"],
      [17, 40, 1, "L"], [18, 52, 1, "L"], [19, 56, 1, "L"], // E2 E3 G#3
      [20, 72, 3, "R"],
      [23, 45, 1, "L"],
      [24, 76, 1, "R"], [25, 75, 1, "R"], [26, 76, 1, "R"], [27, 75, 1, "R"],
      [28, 76, 1, "R"], [29, 71, 1, "R"], [30, 74, 1, "R"], [31, 72, 1, "R"],
      [32, 69, 3, "R"],
      [35, 45, 1, "L"], [36, 52, 1, "L"], [37, 57, 1, "L"],
      [38, 71, 3, "R"],
      [41, 40, 1, "L"], [42, 52, 1, "L"], [43, 56, 1, "L"],
      [44, 72, 1, "R"], [45, 71, 1, "R"],
      [46, 69, 6, "R"], [46, 45, 6, "L"], // land together on the tonic
    ],
  },
  {
    id: "prelude-in-c",
    title: "Prelude in C",
    composer: "Bach",
    step: 0.19, // one sixteenth
    notes: preludeInC(),
  },
];

const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

/**
 * Turn authoring data into everything the player and the canvas need.
 *
 * FINGER ASSIGNMENT IS GESTURAL, NOT PITCH-ACCURATE — deliberately. The hand
 * only drifts ~±26px (PIANO_SHIFT × 2) while a part can span an octave or more,
 * and the keyboard is sized and placed relative to the hand, so literally
 * tracking pitch would slide the hand out from under its own keys. Each
 * left-hand note is instead ranked inside the left-hand part's own range and
 * mapped to one of the five fingers: the eye reads the RHYTHM and the CONTOUR,
 * while the audio carries the true pitch.
 *
 * Right-hand notes are returned in `notes` (so they sound) but are absent from
 * `events` / `strikeSpans`, so they drive no finger.
 *
 * Returns { notes, events, strikeSpans, duration } with all times in SECONDS.
 */
export function compileSong(song) {
  const { step } = song;

  const notes = song.notes
    .map(([unit, midi, durUnits, hand]) => ({
      t: unit * step,
      midi,
      dur: durUnits * step,
      hand,
      finger: null,
    }))
    .sort((a, b) => a.t - b.t || a.midi - b.midi);

  const left = notes.filter((n) => n.hand === "L");
  const lo = left.length ? Math.min(...left.map((n) => n.midi)) : 0;
  const hi = left.length ? Math.max(...left.map((n) => n.midi)) : 1;
  const span = Math.max(1, hi - lo);
  // LEFT-HAND FINGERING IS INVERTED relative to a right hand: the pinky takes the
  // LOWEST notes and the thumb the highest. FINGERS is [thumb, index, middle,
  // ring, pinky], so the lowest pitch maps to 4 and the highest to 0. Getting
  // this backwards is immediately obvious to anyone who plays — the index finger
  // ends up reaching for bass notes the pinky should be on.
  for (const n of left) n.finger = 4 - Math.round(((n.midi - lo) / span) * 4);

  // Group the left hand by strike time — a chord is one event, not three.
  const byTime = new Map();
  for (const n of left) {
    const key = n.t.toFixed(4);
    if (!byTime.has(key)) byTime.set(key, []);
    byTime.get(key).push(n);
  }
  const groups = [...byTime.values()].sort((a, b) => a[0].t - b[0].t);

  let prevFinger = null;
  let prevMidi = null;
  for (const g of groups) {
    if (g.length === 1) {
      const n = g[0];
      // A real player wouldn't restrike one finger across a pitch change (think
      // of the E–D# trill in Für Elise: it alternates). Where the rank mapping
      // repeats a finger, step in the direction the line moved.
      if (prevMidi !== null && n.midi !== prevMidi && n.finger === prevFinger) {
        // Rising pitch moves TOWARD THE THUMB on a left hand, i.e. toward a lower
        // finger index — the opposite of the right-hand instinct.
        const dir = n.midi > prevMidi ? -1 : 1;
        let f = prevFinger + dir;
        // Already on the outermost finger — stepping further would clamp back
        // onto the same one and read as a repeat. Go the other way instead, as
        // a player shifting hand position would.
        if (f < 0 || f > 4) f = prevFinger - dir;
        n.finger = clamp(f, 0, 4);
      }
    } else {
      // A chord: one finger cannot strike two keys, so hand out distinct adjacent
      // fingers around where the rank mapping put the chord. Ordering is
      // left-hand: the LOWEST note of the chord takes the highest finger index
      // (the pinky) and pitch rises toward the thumb — so a bass-plus-chord grip
      // spans the hand the way a real one does.
      g.sort((a, b) => a.midi - b.midi);
      if (g.length > 5) g.length = 5;
      const mean = g.reduce((s, n) => s + n.finger, 0) / g.length;
      const start = clamp(Math.round(mean - (g.length - 1) / 2), 0, 5 - g.length);
      g.forEach((n, i) => { n.finger = start + (g.length - 1 - i); });
    }
    const last = g[g.length - 1];
    prevFinger = last.finger;
    prevMidi = last.midi;
  }

  // `lat` (mean finger, centred on the middle finger) drives the lateral drift.
  const events = groups.map((g) => {
    const f = g.map((n) => n.finger);
    return { t: g[0].t, f, lat: f.reduce((s, x) => s + x, 0) / f.length - 2 };
  });

  // Per finger: [onset, howLongItIsHeld] — NOT just onsets. A finger has to stay
  // down for as long as its note sounds, or the hand blips for a fraction of a
  // second and then sits frozen while you can still hear the note ringing.
  const strikeSpans = [[], [], [], [], []];
  for (const g of groups) for (const n of g) strikeSpans[n.finger].push([n.t, n.dur]);
  for (const arr of strikeSpans) arr.sort((a, b) => a[0] - b[0]);

  // Let the last note ring out rather than cutting the piece off on its attack.
  const last = notes[notes.length - 1];
  const duration = last.t + Math.max(last.dur, 0.6) + 0.5;

  return { notes, events, strikeSpans, duration };
}
